[package]
name = "todo-rust"
version = "0.1.0"
authors = ["Moises Torres <torresmoisesa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
